---
- name: Set timezone to Asia/Bangkok
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get current timezone
      ansible.builtin.command:
        cmd: timedatectl show -p Timezone --value
      register: current_timezone

    - name: Set timezone to Asia/Bangkok if not already set
      ansible.builtin.command:
        cmd: timedatectl set-timezone Asia/Bangkok
      when: current_timezone.stdout != "Asia/Bangkok"
      changed_when: true

    - name: Verify timezone
      ansible.builtin.command:
        cmd: timedatectl
      register: timedatectl_status

    - name: Show timezone status
      ansible.builtin.debug:
        var: timedatectl_status.stdout
